### ISSUE TITLE
Error File not found

### ISSUE THREAD

**Issue by siddharthrawal121** [Param-Raval/editsql-cust#1]
Hi @Param-Raval. Your article on medium was great but there is a slight problem, I did all the steps as you said but got an error. i would really appreciate if you can have a look into it. Thanks in advance.
This is the output and error. :))
```
size of output_vocab 37
output_vocab ['_UNK', '_EOS', '=', 'select', 'value', ')', '(', 'where', ',', 'count', 'group_by', 'order_by', 'distinct', 'and', 'limit_value', 'limit', 'desc', '>', 'avg', 'having', 'max', 'in', '<', 'sum', 'intersect', 'not', 'min', 'except', 'or', 'asc', 'like', '!=', 'union', 'between', '-', '+', '/']

Reading spider database schema file
num_database 166 140 20
total number of schema_tokens / databases: 166
read_data_json data/sparc/train_no_value.json 3034
read_data_json data/sparc/dev_no_value.json 422
interaction_list length 160
train interaction:  3024
dev interaction:  422
Traceback (most recent call last):
  File "run.py", line 12, in <module>
    from data_util import atis_data
  File "/content/drive/My Drive/editsql/data_util/atis_data.py", line 7, in <module>
    from . import atis_batch
  File "/content/drive/My Drive/editsql/data_util/atis_batch.py", line 5, in <module>
    from . import sql_util
  File "/content/drive/My Drive/editsql/data_util/sql_util.py", line 2, in <module>
    import pymysql
ModuleNotFoundError: No module named 'pymysql'
Read prediction from logs_sparc_editsql/valid_use_predicted_queries_predictions.json
Traceback (most recent call last):
  File "postprocess_eval.py", line 466, in <module>
    predictions = read_prediction(pred_file)
  File "postprocess_eval.py", line 384, in read_prediction
    with open(pred_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs_sparc_editsql/valid_use_predicted_queries_predictions.json'
```

**Comment by Param-Raval** [comment]
Hello, thank you for reaching out!

Did you try resolving the `ModuleNotFoundError`? That seems to be the problem since the next `FileNotFoundError` would be resolved if the previous step runs successfully.

`python3 -m pip install pymysql` or `!pip install pymysql` should help.

**Comment by siddharthrawal121** [comment]
Thanks @Param-Raval. That solved the issue but I am getting the error regarding the **glove issue**. I am sure that I have to download the **glove.840B.300d.zip** folder but I am unsure which directory it should go in. I would really appreciate if you can have a look in it. Thanks in advance :))
```
Loading Glove Embedding from /home/lily/rz268/dialog2sql/word_emb/glove.840B.300d.txt
Traceback (most recent call last):
  File "run.py", line 338, in <module>
    main()
  File "run.py", line 301, in main
    data.anonymizer if params.anonymize and params.anonymization_scoring else None)
  File "/content/drive/My Drive/editsql/model/schema_interaction_model.py", line 49, in __init__
    anonymizer)
  File "/content/drive/My Drive/editsql/model/model.py", line 149, in __init__
    input_vocabulary_embeddings, output_vocabulary_embeddings, output_vocabulary_schema_embeddings, input_embedding_size = load_word_embeddings(input_vocabulary, output_vocabulary, output_vocabulary_schema, params)
  File "/content/drive/My Drive/editsql/model/model.py", line 98, in load_word_embeddings
    glove_embeddings = read_glove_embedding(params.embedding_filename, glove_embedding_size)
  File "/content/drive/My Drive/editsql/model/model.py", line 81, in read_glove_embedding
    with open(embedding_filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/lily/rz268/dialog2sql/word_emb/glove.840B.300d.txt'
Read prediction from logs_sparc_editsql/valid_use_predicted_queries_predictions.json
Traceback (most recent call last):
  File "postprocess_eval.py", line 466, in <module>
    predictions = read_prediction(pred_file)
  File "postprocess_eval.py", line 384, in read_prediction
    with open(pred_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs_sparc_editsql/valid_use_predicted_queries_predictions.json'
```

**Comment by siddharthrawal121** [comment]
Hi, regarding the last issue. I fixed it by changing the path in **run_sparc_editsql** of GLOVE_PATH.
