### ISSUE TITLE
glove.840B.300d.txt

### ISSUE THREAD

**Issue by imanuelroz** [Param-Raval/editsql-cust#6]
Hi Param, 

I followed all your step, but in addition I also downloaded the glove.840B.300d.txt and change the path in the corresponding run_sparc_edistql.sh file and test_sparc_editsql.sh file and when I run the run_sparc_edistql.sh file it gives me the following Error: 

```
Loading Glove Embedding from /content/gdrive/MyDrive/practica/glove.840B.300d.txt
Traceback (most recent call last):
  File "run.py", line 338, in <module>
    main()
  File "run.py", line 301, in main
    data.anonymizer if params.anonymize and params.anonymization_scoring else None)
  File "/content/gdrive/My Drive/practica/editsql/model/schema_interaction_model.py", line 49, in __init__
    anonymizer)
  File "/content/gdrive/My Drive/practica/editsql/model/model.py", line 149, in __init__
    input_vocabulary_embeddings, output_vocabulary_embeddings, output_vocabulary_schema_embeddings, input_embedding_size = load_word_embeddings(input_vocabulary, output_vocabulary, output_vocabulary_schema, params)
  File "/content/gdrive/My Drive/practica/editsql/model/model.py", line 98, in load_word_embeddings
    glove_embeddings = read_glove_embedding(params.embedding_filename, glove_embedding_size)
  File "/content/gdrive/My Drive/practica/editsql/model/model.py", line 91, in read_glove_embedding
    embedding = np.array([float(val) for val in l_split[-embedding_size:]])
  File "/content/gdrive/My Drive/practica/editsql/model/model.py", line 91, in <listcomp>
    embedding = np.array([float(val) for val in l_split[-embedding_size:]])
ValueError: could not convert string to float: 'squeeze2'
Read prediction from logs_sparc_editsql/valid_use_predicted_queries_predictions.json
Number of predictions 1203
Eval result in logs_sparc_editsql/valid_use_predicted_queries_predictions.json.eval
```

Could you help me? If I don't change the directory in GLOVE_PATH and leave it as it is I also have problems.

Thank you in advance.

**Comment by Param-Raval** [comment]
I'm not sure about this error. However, it seems unrelated to the editsql code. Maybe the way you read the GloVe file is causing an issue. My advice would be to trace the error through the files and debug what's the problem (like logging "val" or checking the file reading in `read_glove_embedding`).
